### ISSUE TITLE
comma separate

### ISSUE THREAD

**Issue by twixi** [haniokasai/BreakMoney#1]
numbers do not work with a comma!
`
//id: //momey
'17': '0.1'
'15': '0.1'
'14': '0.1'
'1': '0.1'
'16': '0.1'
'56': ''0.3'
'73': ''0.3'
'74': ''0.2'
`
its have error:

`2017-4-17 21:56:56 [CRITICAL] "Не зміг пройти 'cn.nukkit.event.block.BlockBreakEvent' подій для 'BreakMoney v0.0.1': null на com.haniokasai.nukkit.BreakMoney.Main
2017-4-17 21:56:56 [ALERT] cn.nukkit.utils.EventException
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
	at cn.nukkit.level.Level.useBreakOn(Level.java:1700)
	at cn.nukkit.Player.handleDataPacket(Player.java:2687)
	at cn.nukkit.network.Network.processPackets(Network.java:185)
	at cn.nukkit.network.Network.processBatch(Network.java:156)
	at cn.nukkit.Player.handleDataPacket(Player.java:1895)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:155)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:64)
	at cn.nukkit.network.Network.processInterfaces(Network.java:76)
	at cn.nukkit.Server.tick(Server.java:1010)
	at cn.nukkit.Server.tickProcessor(Server.java:808)
	at cn.nukkit.Server.start(Server.java:787)
	at cn.nukkit.Server.<init>(Server.java:472)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: java.lang.NumberFormatException: For input string: "0.1"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.<init>(Unknown Source)
	at com.haniokasai.nukkit.BreakMoney.Main.onBlockBreak(Main.java:50)
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
	... 16 more`

**Comment by haniokasai** [comment]
hmm...
i overlooked this issue...
